include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_use_package_imports: true
    always_declare_return_types: true
    sort_pub_dependencies: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    prefer_single_quotes: true
    combinators_ordering: true
    directives_ordering: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_conditional_assignment: true
    prefer_collection_literals: true
    prefer_contains: true
    prefer_final_in_for_each: true
    prefer_final_parameters: true
    prefer_inlined_adds: true
    prefer_is_empty: true
    prefer_null_aware_operators: true
    public_member_api_docs: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    todo: ignore