name: expandable_tile
description: A package that provides a expandable tile with controllers
version: 1.0.1
homepage: https://github.com/2-5-perceivers/expandable-tile

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.2.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
